title: Nguyen Pham Bich Ngoc
logo: assets/img/hehe.jpg
# description: Aspiring Data Scientist Intern with a passion for data analysis and machine learning
# show_downloads: true
theme: jekyll-theme-minimal
